sudo: required
services:
    - docker

before_install:
    - docker build -t ranaivoson0/formation-client-test -f ./client/Dockerfile.dev ./client
    - docker build -t ranaivoson0/formation-api-test -f ./api/build/nginx/Dockerfile.dev ./api/build/nginx
    - docker build -t ranaivoson0/formation-php-test -f ./api/Dockerfile.dev ./api

script:
    - docker run ranaivoson0/formation-client-test npm test -- --coverage
    - php ./api/bin/phpunit

after_success:
    - docker build -t ranaivoson0/formation-client ./client
    - docker build -t ranaivoson0/formation-proxy ./proxy
    - docker build -t ranaivoson0/formation-api ./api/build/nginx
    - docker build -t ranaivoson0/formation-php ./api
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push ranaivoson0/formation-client
    - docker push ranaivoson0/formation-proxy
    - docker push ranaivoson0/formation-api
    - docker push ranaivoson0/formation-php