version: '3'
services:
  api:
    build:
      context: ./api/build/nginx
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - /app/vendor
      - ./api:/app
  redis:
    image: 'redis:latest'
  rabbitmq:
    image: 'rabbitmq:3.8-rc-management'
    environment:
      RABBITMQ_DEFAULT_USER: formation
      RABBITMQ_DEFAULT_PASS: formation
    ports:
      - '15672:15672'
      - "5672:5672"
    restart: always
    volumes:
      - ./api/build/rabbitmq:/var/lib/rabbitmq/mnesia
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_PASSWORD=pg_password
  php:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /app/vendor
      - ./api:/app
    ports:
      - '9000:9000'
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile.dev
    ports:
      - '80:80'
    restart: always