security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        # use your user class name here
        App\Entity\User:
            # bcrypt or argon2i are recommended
            # argon2i is more secure, but requires PHP 7.2 or the Sodium extension
            algorithm: argon2i
            cost: 12
    providers:
#        in_memory: { memory: ~ }
        users:
            entity:
                class: 'App\Entity\User'
                property: 'username'
    firewalls:
        main:
            pattern: ^/
            stateless: true
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
            json_login:
                check_path: login
                success_handler: App\Security\AuthenticationSuccessHandler
                failure_handler: App\Security\AuthenticationFailureHandler

    access_control:
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER